plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.9'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.ConcertFinder'
version = '0.0.1-SNAPSHOT'
description = 'ConcertFinder'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // JPA 의존성
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // 타임리프 의존성
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // 롬북 의존성
    compileOnly 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    // mysql 커넥터 의존성
    runtimeOnly 'com.mysql:mysql-connector-j'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // 타임리프 레이아웃 의존성
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect'

    // OpenAPI 연동용 웹 플럭스 의존성
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // 맥북 DNS 오류 해결 의존성
    runtimeOnly 'io.netty:netty-resolver-dns-native-macos:4.1.104.Final:osx-aarch_64'

    // 쿼리 결과 확인 의존성
    implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.9.0'

    // xml과 객체 매핑 도움 의존성
    implementation 'org.glassfish.jaxb:jaxb-runtime:4.0.4'
    implementation 'jakarta.xml-bind:jakarta.xml.bind-api:4.0.1'
}

tasks.named('test') {
    useJUnitPlatform()
}
